namespace SBFCrawler;

public class VehicleDetail
{
    public string customer_id { get; set; }
    public string dealer_name { get; set; }
    public Vhr vhr { get; set; }
    public string trip_id { get; set; }
    public object marketing_click_data { get; set; }
    public string vertical_position { get; set; }
    public string page_type { get; set; }
    public int photo_count { get; set; }
    public string mileage { get; set; }
    public string profileAccountType { get; set; }
    public string trim { get; set; }
    public bool loginStatus { get; set; }
    public string make { get; set; }
    public string local_zone { get; set; }
    public object utm_source { get; set; }
    public string msrp { get; set; }
    public string page_name { get; set; }
    public object page_detail { get; set; }
    public string market_name { get; set; }
    public object utm_medium { get; set; }
    public string drivetrain { get; set; }
    public bool cpo_indicator { get; set; }
    public string useragent { get; set; }
    public string model { get; set; }
    public string private_seller { get; set; }
    public string url_referer { get; set; }
    public string vin { get; set; }
    public object utm_term { get; set; }
    public string designated_market_area_key { get; set; }
    public string canonical_mmt { get; set; }
    public string seller_type { get; set; }
    public string fuel_type { get; set; }
    public string stock_sub { get; set; }
    public string stock_type { get; set; }
    public string listing_id { get; set; }
    public object utm_campaign { get; set; }
    public string canonical_mmty { get; set; }
    public List<string> page_features { get; set; }
    public string lat_long { get; set; }
    public string page_key { get; set; }
    public string interior_color { get; set; }
    public string search_instance_id { get; set; }
    public object price_badge { get; set; }
    public string platform_id { get; set; }
    public bool sponsored { get; set; }
    public string aff_code { get; set; }
    public List<string> badges { get; set; }
    public string zip_ip2geo { get; set; }
    public string dealer_zip { get; set; }
    public string page_channel { get; set; }
    public object utm_content { get; set; }
    public string url_base { get; set; }
    public string partner_name { get; set; }
    public string price { get; set; }
    public string exterior_color { get; set; }
    public string dealer_dma { get; set; }
    public string bodystyle { get; set; }
    public string marketing_click_id { get; set; }
    public string marketing_referral_source { get; set; }
    public object seller_id { get; set; }
    public string cat { get; set; }
    public string year { get; set; }
}